export const API_ENDPOINTS = {
  auth: {
    register: '/api/auth/register',
    login: '/api/auth/login',
    refresh: '/api/auth/refresh',
  },
  semestres: {
    getAll: '/api/semestres',
    getById: (id: string) => `/api/semestres/${id}`,
    create: '/api/semestres',
    update: (id: string) => `/api/semestres/${id}`,
    delete: (id: string) => `/api/semestres/${id}`,
    activar: (id: string) => `/api/semestres/${id}/activar`,
  },
  materias: {
    getAll: '/api/materias',
    getById: (id: string) => `/api/materias/${id}`,
    create: '/api/materias',
    update: (id: string) => `/api/materias/${id}`,
    delete: (id: string) => `/api/materias/${id}`,
  },
  tareas: {
    getAll: '/api/tareas',
    getById: (id: string) => `/api/tareas/${id}`,
    create: '/api/tareas',
    update: (id: string) => `/api/tareas/${id}`,
    delete: (id: string) => `/api/tareas/${id}`,
    updateStatus: (id: string) => `/api/tareas/${id}/status`,
  },
  horario: {
    getAll: '/api/horario',
    getById: (id: string) => `/api/horario/${id}`,
    create: '/api/horario',
    update: (id: string) => `/api/horario/${id}`,
    delete: (id: string) => `/api/horario/${id}`,
  },
  temarios: {
    parciales: {
      getAll: '/api/temarios/parciales',
      getById: (id: string) => `/api/temarios/parciales/${id}`,
      create: '/api/temarios/parciales',
      update: (id: string) => `/api/temarios/parciales/${id}`,
      delete: (id: string) => `/api/temarios/parciales/${id}`,
    },
    items: {
      getAll: '/api/temarios/items',
      getById: (id: string) => `/api/temarios/items/${id}`,
      create: '/api/temarios/items',
      update: (id: string) => `/api/temarios/items/${id}`,
      delete: (id: string) => `/api/temarios/items/${id}`,
    },
  },
  calificaciones: {
    criterios: {
      getAll: '/api/calificaciones/criterios',
      getById: (id: string) => `/api/calificaciones/criterios/${id}`,
      create: '/api/calificaciones/criterios',
      update: (id: string) => `/api/calificaciones/criterios/${id}`,
      delete: (id: string) => `/api/calificaciones/criterios/${id}`,
    },
    getAll: '/api/calificaciones',
    getById: (id: string) => `/api/calificaciones/${id}`,
    create: '/api/calificaciones',
    update: (id: string) => `/api/calificaciones/${id}`,
    delete: (id: string) => `/api/calificaciones/${id}`,
    promedio: (materiaId: string) => `/api/calificaciones/promedio/${materiaId}`,
    proyeccion: (materiaId: string) => `/api/calificaciones/proyeccion/${materiaId}`,
  },
  apuntes: {
    getAll: '/api/apuntes',
    getById: (id: string) => `/api/apuntes/${id}`,
    getByMateria: (materiaId: string) => `/api/apuntes/materia/${materiaId}`,
    create: '/api/apuntes',
    update: (id: string) => `/api/apuntes/${id}`,
    delete: (id: string) => `/api/apuntes/${id}`,
  },
  dashboard: {
    resumen: '/api/dashboard/resumen',
    proximasEntregas: '/api/dashboard/proximas-entregas',
  },
} as const;
